---
title: "STAT 184 Homework Exercises" 
subtitle: "DataComputing Chapters 13 & 16"
author: "eric weah "
output: html_notebook
---

## Assigned Exercises

- DC Chapter 13 Exercises: All 
- DC Chapter 16 Exercises:

## Front Matter

```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(mosaic)
library(tidyverse)
library(DataComputing)
library(lubridate)
library(ggplot2)
```



## Chapter 13 Exercises

### Problem 13.1
```{r}
BabyNames%>%
  group_by(sex,name)%>%
  filter(sex=="F")%>%
  summarise(total=sum(count))%>%
  arrange(desc(total))%>%
  head(5)
BabyNames%>%
  group_by(sex,name)%>%
  filter(sex=="M")%>%
  summarise(total=sum(count))%>%
  arrange(desc(total))%>%
  head(5)
```

### Problem 13.2
a.)
```{r}
Names_Pop<-
  BabyNames%>%
  group_by(year)%>%
  filter(rank(desc(count)) <= 100)%>%
  summarise(total=sum(count))%>%
  arrange(desc(year))%>%
  mutate(ranking="Top_100")
Names_Pop
 
```
b.)
```{r}
Top100<-
  Names_Pop%>%
  spread(key = ranking,value=total)%>%
  arrange(desc(year))%>%
  mutate(FractionB=(Top_100)/ (Top_100))
Top100
```
c.)
```{r}
Top100%>%
  ggplot(aes(x=year, y = FractionB))+
  geom_point()+ggtitle("POP VS TIME")+
  xlab("Year")+ylab("Fraction of babies")
```
### Problem 13.3
```{r}
PopNames<-
  BabyNames%>%
  group_by(year)%>%
  mutate(ranking=rank(desc(count)))%>%
  filter(rank(desc(count))<=50)%>%
  group_by(name)%>%
  summarise(sum(count))
PopNames
```

```{r}
UnPop<-
  BabyNames%>%
  group_by(year)%>%
  mutate(ranking=rank(desc(count)))%>%
  filter(rank(desc(count))>1000)%>%
  group_by(name)%>%
  summarise(sum(count))
UnPop
```
```{r}
JOIN<-
  PopNames%>%
  inner_join(UnPop, by = "name")
JOIN
```

## Chapter 16 Exercises

### Problem 16.1
a.) 
```{r}
ymd("1998-12-14")-
mdy("April 30, 1777")
```
b.
```{r}
ymd("1998-12-14")-
mdy("06-23-1912")
```
c.)
```{r}
ymd("1998-12-14")-
dmy("3 march 1847")
```
d
```{r}
ymd("1998-12-14")-
mdy("July 28th, 1914")
```
e.)
```{r}
ymd("1998-12-14")-
  mdy("July 28th, 1914")
```
### Problem 16.2

